In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/credit-card-customer-churn-prediction/Churn_Modelling.csv


In [2]:
df=pd.read_csv('/kaggle/input/credit-card-customer-churn-prediction/Churn_Modelling.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df.shape

(10000, 14)

In [5]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [7]:
df['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [8]:
df.duplicated().sum()

0

In [9]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [10]:
df['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [11]:
df['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [12]:
df.drop(columns=['RowNumber', 'CustomerId', 'Surname'], inplace=True)

ohe on gender and geography

In [13]:
df=pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first=True)

In [14]:
df.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0               1        101348.88       1                  0   
1               1        112542.58       0                  0   
2               0        113931.57       1                  0   
3               0         93826.63       0                  0   
4               1         79084.10       0                  0   

   Geography_Spain  Gender_Male  
0                0            0  
1                1            0  
2                0            0  
3                0            0  
4                1            0

In [15]:

from sklearn.model_selection import train_test_split

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [16]:
X=df.drop('Exited', axis=1)

In [17]:
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
0               1        101348.88                  0                0   
1               1        112542.58                  0                1   
2               0        113931.57                  0                0   
3               0         93826.63                  0                0   
4               1         79084.10                  0                1   

   Gender_Male  
0            0  
1            0  
2            0  
3            0  
4            0

In [18]:
y=df['Exited']
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [19]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=1)

In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
ss=StandardScaler()

In [22]:
X_train_sc=ss.fit_transform(X_train)
X_test_sc=ss.fit_transform(X_test)


In [23]:
X_train_sc

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [24]:
import warnings
warnings.filterwarnings('ignore')

In [25]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense #to  create dense layer

In [26]:
#pahle model obj banao
# fir layers add kro

In [27]:
model=Sequential()

#hidden layer-
model.add(Dense(3, activation='sigmoid', input_dim=11))
#3- no. of nodes
# input_dim= feauters

#o/p layer-
model.add(Dense(1, activation='sigmoid'))


In [28]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 36        
                                                                 
 dense_1 (Dense)             (None, 1)                 4         
                                                                 
Total params: 40
Trainable params: 40
Non-trainable params: 0
_________________________________________________________________


model compilation stage me kuch cheeze batate ho ex- konsa loss function use kroge, konsa optimizer use kroge gradient descent k liye

In [29]:
model.compile(loss='binary_crossentropy', optimizer='Adam'  )

In [30]:
model.fit(X_train_sc, y_train, epochs=10)

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 0.6113
Epoch 2/10
250/250 [==============================] - 0s 1ms/step - loss: 0.5155
Epoch 3/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4746
Epoch 4/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4586
Epoch 5/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4505
Epoch 6/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4451
Epoch 7/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4409
Epoch 8/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4376
Epoch 9/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4347
Epoch 10/10
250/250 [==============================] - 0s 1ms/step - loss: 0.4324


In [33]:
#hmara model  train ho chuka he ex- weights n biases calculate ho chuke he

**Calculated weights and biases of 1st layer:-**

In [36]:
model.layers[0].get_weights()

[array([[ 0.39344582,  0.12600571, -0.1572927 ],
        [-0.9056274 , -2.0343516 , -1.9534706 ],
        [ 0.33974797,  0.02102856, -0.12404726],
        [-0.01683356, -0.6579512 , -0.48288882],
        [ 0.56742597, -0.08031919, -0.13875727],
        [ 0.0300228 , -0.01910547,  0.02644017],
        [ 1.2158878 ,  0.74471813,  0.7721374 ],
        [-0.3794421 ,  0.16243677,  0.01622219],
        [-0.64967084, -0.3923027 , -0.8173787 ],
        [ 0.08262937, -0.27155197,  0.17598626],
        [ 0.5980725 ,  0.5089922 ,  0.56072813]], dtype=float32),
 array([0.52942955, 0.4370509 , 0.47518638], dtype=float32)]

**Calculated weights and biases of 2nd layer:-**

In [37]:
model.layers[1].get_weights()

[array([[-0.64359534],
        [-0.9191566 ],
        [-0.8843458 ]], dtype=float32),
 array([-0.20263007], dtype=float32)]

**Predictions:**

In [38]:
model.predict(X_test_sc) # will o/p in range(0,1) since sigmoid is used

63/63 [==============================] - 0s 1ms/step


array([[0.10708434],
       [0.1379354 ],
       [0.12196353],
       ...,
       [0.07084593],
       [0.13198847],
       [0.3321049 ]], dtype=float32)

ab isko categories me convert krne  liye we need a threshold(ex- 0.5(say) )

But to decide the good threshold we plot curves like- ROC, AOC, AUC curves(filhaal 0.5 se kaam chala lete he)

In [39]:
y_log=model.predict(X_test_sc)

63/63 [==============================] - 0s 1ms/step


In [40]:
y_pred=np.where(y_log>0.5,1,0)

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7925

# **Chalo layers, nodes, activation funcs chnage krke dekhte he-**

In [43]:
#zada layers se overfitting hone lgta he

In [44]:
model=Sequential()

model.add(Dense(11, activation='relu', input_dim=11))
model.add(Dense(11, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


In [45]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 11)                132       
                                                                 
 dense_3 (Dense)             (None, 11)                132       
                                                                 
 dense_4 (Dense)             (None, 1)                 12        
                                                                 
Total params: 276
Trainable params: 276
Non-trainable params: 0
_________________________________________________________________


In [46]:
model.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'] )

In [47]:
model.fit(X_train_sc, y_train, epochs=100, validation_split=0.2)

Epoch 1/100
200/200 [==============================] - 1s 3ms/step - loss: 0.5354 - accuracy: 0.7805 - val_loss: 0.4727 - val_accuracy: 0.7975
Epoch 2/100
200/200 [==============================] - 0s 2ms/step - loss: 0.4505 - accuracy: 0.8027 - val_loss: 0.4354 - val_accuracy: 0.8081
Epoch 3/100
200/200 [==============================] - 0s 2ms/step - loss: 0.4246 - accuracy: 0.8153 - val_loss: 0.4211 - val_accuracy: 0.8144
Epoch 4/100
200/200 [==============================] - 0s 2ms/step - loss: 0.4109 - accuracy: 0.8233 - val_loss: 0.4070 - val_accuracy: 0.8275
Epoch 5/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3961 - accuracy: 0.8316 - val_loss: 0.3922 - val_accuracy: 0.8325
Epoch 6/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3821 - accuracy: 0.8398 - val_loss: 0.3797 - val_accuracy: 0.8375
Epoch 7/100
200/200 [==============================] - 0s 2ms/step - loss: 0.3720 - accuracy: 0.8461 - val_loss: 0.3704 - val_accuracy: 0.8413

In [48]:
# jo trainig ho rhi he uska loss, jo trainig ho rhi he uski accuracy, validation set ka loss(20%wala, abhi jo liya that is being use for validation on each epoch, val set ki accuracy) 

In [50]:
# training accuracy ~ 87%, val_accuracy ~ 81% here => thoda overfitting he isme

In [51]:
y_log=model.predict(X_test_sc)

63/63 [==============================] - 0s 1ms/step


In [52]:
y_pred=np.where(y_log>0.5,1,0)

In [53]:
accuracy_score(y_test, y_pred)

0.8615