In [14]:
import numpy as np
import pandas as pd

In [15]:
df=pd.DataFrame([[8,8,4], [7, 9, 5], [6, 10, 6], [5, 12, 7]], columns=['cgpa', 'profile_score', 'lpa'])

In [16]:
df.head()

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [17]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [18]:
model=Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

In [19]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.get_weights()

[array([[ 0.6120851 , -0.61622953],
        [ 0.65308833,  0.3218037 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.71119964],
        [0.25663114]], dtype=float32),
 array([0.], dtype=float32)]

In [21]:
new_weights=[np.array([[0.1, 0.1],
                       [0.1, 0.1]], dtype=np.float32),
             np.array([0., 0.], dtype=np.float32),
             np.array([[0.1], [0.1]], dtype=np.float32),
             np.array([0.], dtype=np.float32)] #w's=1, b's=0

In [22]:
model.set_weights(new_weights)

In [23]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [24]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [25]:
model.fit(df.iloc[:,:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 [==============================] - 0s 3ms/step - loss: 27.8792
Epoch 2/75
4/4 [==============================] - 0s 4ms/step - loss: 27.5620
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 27.2411
Epoch 4/75
4/4 [==============================] - 0s 2ms/step - loss: 26.8850
Epoch 5/75
4/4 [==============================] - 0s 2ms/step - loss: 26.5692
Epoch 6/75
4/4 [==============================] - 0s 2ms/step - loss: 26.2060
Epoch 7/75
4/4 [==============================] - 0s 2ms/step - loss: 25.8252
Epoch 8/75
4/4 [==============================] - 0s 2ms/step - loss: 25.4358
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 25.0639
Epoch 10/75
4/4 [==============================] - 0s 3ms/step - loss: 24.6289
Epoch 11/75
4/4 [==============================] - 0s 3ms/step - loss: 24.2465
Epoch 12/75
4/4 [==============================] - 0s 3ms/step - loss: 23.7957
Epoch 13/75
4/4 [==============================] - 0s 3ms/ste

In [26]:
model.get_weights()

[array([[0.3738627 , 0.3738627 ],
        [0.36591327, 0.36591327]], dtype=float32),
 array([0.27258968, 0.27258968], dtype=float32),
 array([[0.3731961],
        [0.3731961]], dtype=float32),
 array([0.20498349], dtype=float32)]