In [1]:
import pandas as pd
import numpy as np
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [2]:
df=pd.DataFrame([[8,8,1], [7,9,1], [6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [3]:
df.head()

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [5]:
model=Sequential()

model.add(Dense(2, activation='sigmoid', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

In [6]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.get_weights()

[array([[-0.97422445, -0.04196131],
        [ 0.31996548, -0.74152344]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[1.0750264 ],
        [0.14906192]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy', optimizer=optimizer)

In [10]:
model.fit(df.iloc[:,:-1].values, df['placed'].values, epochs=50, verbose=1, batch_size=1)

Epoch 1/50
4/4 [==============================] - 1s 10ms/step - loss: 0.7043
Epoch 2/50
4/4 [==============================] - 0s 8ms/step - loss: 0.7042
Epoch 3/50
4/4 [==============================] - 0s 9ms/step - loss: 0.7036
Epoch 4/50
4/4 [==============================] - 0s 5ms/step - loss: 0.7035
Epoch 5/50
4/4 [==============================] - 0s 8ms/step - loss: 0.7030
Epoch 6/50
4/4 [==============================] - 0s 5ms/step - loss: 0.7028
Epoch 7/50
4/4 [==============================] - 0s 5ms/step - loss: 0.7026
Epoch 8/50
4/4 [==============================] - 0s 11ms/step - loss: 0.7023
Epoch 9/50
4/4 [==============================] - 0s 10ms/step - loss: 0.7021
Epoch 10/50
4/4 [==============================] - 0s 5ms/step - loss: 0.7018
Epoch 11/50
4/4 [==============================] - 0s 3ms/step - loss: 0.7017
Epoch 12/50
4/4 [==============================] - 0s 4ms/step - loss: 0.7016
Epoch 13/50
4/4 [==============================] - 0s 4ms/step - loss: